version: '3.8'

networks:
  proxy_next:
    name: proxy_next
    driver: overlay
    attachable: true

services:
  node:
    image: $DOCKER_IMAGE
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.service == apps
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
    environment:
      ELASTICSEARCH_NEXT_ADDRESS: $ELASTICSEARCH_NEXT_ADDRESS
      ELASTICSEARCH_7_14_ADDRESS: $ELASTICSEARCH_7_14_ADDRESS
      ELASTICSEARCH_8_X_ADDRESS: $ELASTICSEARCH_8_X_ADDRESS
      TZ: utc
      NODE_ENV: production
    ports:
      - 6001:8001
      - 6002:8002
    networks:
      - proxy_next