version = 0.1
default-task = 'start'

extensions = ['chomp@0.1:prettier']

[[task]]
name = 'start'
env = { TZ='UTC', NODE_ENV='development', NODE_TLS_REJECT_UNAUTHORIZED='0'}
deps = [ 'src/**/*.js' ]
run = """
node \
  --trace-warnings \
  --experimental-json-modules \
  src
"""

[[task]]
name = 'prettier'
template = 'prettier'
[task.template-options]
ignore-path = '.prettierignore'
files = 'src/**/*.@(js|json|yml)'
loglevel = 'warn'
config = '.prettierrc'

[[task]]
name = 'reset'
run = """
rm -rf node_modules
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} + \
    && find . \
      -name package-lock.json \
      -type f \
      -delete
"""