version = 0.1
default-task = 'start'

[[task]]
name = 'ncu'
run = 'ncu'

[[task]]
name = 'ncu:u'
run = 'ncu -u'

[[task]]
name = 'start'
env = { NODE_ENV = 'development', TZ = 'utc' }
run = """
  nodemon \
    --watch ./src \
    --exec 'node --trace-warnings --experimental-json-modules src'
"""

[[task]]
name = 'reset'
run = """
rm -rf node_modules
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} + \
    && find . \
      -name package-lock.json \
      -type f \
      -delete
"""